#include "Config.h"
#include "Platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#if defined(PLATFORM_WINDOWS)
    #include <windows.h>
    #include <bcrypt.h>
    #ifdef _MSC_VER
        #pragma comment(lib, "bcrypt.lib")  //For Windows shitty compiler
    #endif
#elif defined(PLATFORM_APPLE)
    #include <unistd.h>
    #include <stdlib.h>
#elif defined(PLATFORM_LINUX)
    #include <sys/random.h>
    #include <unistd.h>
#endif

unsigned int GetHardwareThreadCount(void)
{
    static unsigned int ThreadCount = 0; 
    if (ThreadCount != 0) 
      return ThreadCount;

#if SUPPORT_MULTITHREADING == 1
    #if defined(PLATFORM_WINDOWS)
        SYSTEM_INFO sysinfo;
        GetSystemInfo(&sysinfo);
        ThreadCount = (unsigned int)sysinfo.dwNumberOfProcessors;

    #elif defined(PLATFORM_APPLE) || defined(PLATFORM_LINUX)
        long cores = sysconf(_SC_NPROCESSORS_ONLN);
        ThreadCount = (cores < 1) ? 1 : (unsigned int)cores;
    #endif
#else
    ThreadCount = 1;
#endif

    if (ThreadCount == 0) ThreadCount = 1;
       return ThreadCount;
}

bool GenerateSecureRandomBytes(uint8_t* buffer, size_t length) 
{
  if (buffer == NULL || length == 0) return false;

  #if defined(PLATFORM_WINDOWS)
    NTSTATUS status = BCryptGenRandom(NULL, buffer, (ULONG)length, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
    return (status == 0); // SUCCES STATUS is 0

  #elif defined(PLATFORM_APPLE)
    arc4random_buf(buffer, length);
    return true;

  #elif defined(PLATFORM_LINUX)
    ssize_t result = getrandom(buffer, length, 0);
    return (result == (ssize_t)length);
    
  #else 
    return false;

  #endif

}

int8_t GetSecureRandomDigit(bool allowZero) //Generate one truly random digit from [0-9] or [1-9] depending on allowZero
{
    // In order to get rid of Modulo Bias we set limits
    // A randomly generated byte takes a value between 0-255 but we want a perfectly uniform distribution of modulo 10 (with or without 0)
    // We define the following limits based on allowZero
    // For 0-9  : 0-249   (allowZero is true)
    // For 1-9  : 0-251   (allowZero is false)

    uint8_t limit  = allowZero ? 250 : 252; 
    uint8_t modulo = allowZero ? 10 : 9;
    uint8_t offset = allowZero ? 0 : 1;
    
    uint8_t byte;
    while(true)
    {
        // Generate a criptographic safe byte
        if (!GenerateSecureRandomBytes(&byte,1)) 
        {
            perror("ERROR OCURED DURING RANDOM GENERATION\n");
            exit(-1);
        }
        
        //If the byte doesnt obey our limits we generate a new one
        if (byte<limit) 
        {
            return (byte%modulo)+offset;
        }
    }
}
